# -*- coding: utf-8 -*-
"""MatchMomentum: IPL Victory Odds Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjDyX9ltKaP9VBZZG-IRT4n1fe55LX3s
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

match = pd.read_csv('/content/drive/MyDrive/IPL_predictor/matches.csv')
delivery = pd.read_csv('/content/drive/MyDrive/IPL_predictor/deliveries.csv')

match.head()

delivery.head()

total_score_df = delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

total_score_df.head()

total_score_df = total_score_df[total_score_df['inning'] == 1]

total_score_df

match_df = match.merge(total_score_df[['match_id','total_runs']], left_on='id', right_on='match_id')

match_df

match_df['team2'].unique()

teams = [
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Rajasthan Royals',
    'Chennai Super Kings',
    'Delhi Capitals'
]

match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

match_df

match_df = match_df[match_df['dl_applied'] == 0]

match_df.shape

match_df = match_df[['match_id','city','winner','total_runs']]

match_df

delivery_df = match_df.merge(delivery, on='match_id')

delivery_df.head()

delivery_df = delivery_df[delivery_df['inning'] == 2]

delivery_df

delivery_df['current_score'] = delivery_df.groupby('match_id').cumsum()['total_runs_y']

delivery_df.head()

delivery_df['runs_left'] = delivery_df['total_runs_x'] - delivery_df['current_score']

delivery_df.head()

delivery_df['balls_left'] = 126 - (delivery_df['over']*6 + delivery_df['ball'])

delivery_df.head()

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x if x == "0" else "1")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')

delivery_df

wickets = delivery_df.groupby('match_id').cumsum()['player_dismissed'].values
delivery_df['wickets'] = 10 - wickets

delivery_df.tail()

#crr = runs/(balls/6)
delivery_df['crr'] = (delivery_df['current_score']*6)/(120 - delivery_df['balls_left'])

delivery_df.head()

delivery_df['rrr'] = (delivery_df['runs_left']*6)/delivery_df['balls_left']

delivery_df.head()

def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

delivery_df['result'] = delivery_df.apply(result,axis=1)

delivery_df.head()

final_df = delivery_df[['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left', 'wickets', 'total_runs_x', 'crr', 'rrr', 'result']]

final_df.head()

final_df = final_df.sample(final_df.shape[0])

final_df.head()

final_df.isnull().sum()

final_df.dropna(inplace=True)

final_df = final_df[final_df['balls_left'] != 0]

"""MODEL BUILDING BEGINS"""

X = final_df.iloc[:,:-1]
y = final_df.iloc[:, -1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state = 1)

X_train

y_train

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer(
    [('trf',OneHotEncoder(sparse=False,drop='first'),
      ['batting_team','bowling_team','city'])],
    remainder = 'passthrough')

from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

pipe.predict_proba(X_test)

def match_summary(row):
    print("Batting Team-" + row['batting_team'] + " | Bowling Team-" + row['bowling_team'] + " | Target- " + str(row['total_runs_x']))

# Match progression chart function
def match_progression_chart(temp_df, target):
    plt.figure(figsize=(18, 8))
    plt.plot(temp_df['end_of_over'], temp_df['wickets_in_over'], color='yellow', linewidth=3)
    plt.plot(temp_df['end_of_over'], temp_df['win'], color='#00a65a', linewidth=4)
    plt.plot(temp_df['end_of_over'], temp_df['lose'], color='red', linewidth=4)
    plt.bar(temp_df['end_of_over'], temp_df['runs_after_over'])
    plt.title('Target-' + str(target))
    plt.xlabel('Over')
    plt.ylabel('Runs/Wickets')
    plt.legend(['Wickets', 'Win Probability', 'Lose Probability', 'Runs Scored'])
    plt.grid(True)
    plt.show()

def match_progression(x_df,match_id,pipe):
    match = x_df[x_df['match_id'] == match_id]
    match = match[(match['ball'] == 6)]
    temp_df = match[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_x','crr','rrr']].dropna()
    temp_df = temp_df[temp_df['balls_left'] != 0]
    result = pipe.predict_proba(temp_df)
    temp_df['lose'] = np.round(result.T[0]*100,1)
    temp_df['win'] = np.round(result.T[1]*100,1)
    temp_df['end_of_over'] = range(1,temp_df.shape[0]+1)

    target = temp_df['total_runs_x'].values[0]
    runs = list(temp_df['runs_left'].values)
    new_runs = runs[:]
    runs.insert(0,target)
    temp_df['runs_after_over'] = np.array(runs)[:-1] - np.array(new_runs)
    wickets = list(temp_df['wickets'].values)
    new_wickets = wickets[:]
    new_wickets.insert(0,10)
    wickets.append(0)
    w = np.array(wickets)
    nw = np.array(new_wickets)
    temp_df['wickets_in_over'] = (nw - w)[0:temp_df.shape[0]]

    print("Target-",target)
    temp_df = temp_df[['end_of_over','runs_after_over','wickets_in_over','lose','win']]
    return temp_df,target

temp_df,target = match_progression(delivery_df,74,pipe)
temp_df

match_progression_chart(temp_df, target)

"""**Comparing the number of matches won by different teams**"""

import seaborn as sns
import matplotlib.pyplot as plt

team_wins = match_df['winner'].value_counts().reset_index()
team_wins.columns = ['Team', 'Wins']

plt.figure(figsize=(12, 6))
sns.barplot(x='Wins', y='Team', data=team_wins, palette='Set1')
plt.title('Number of Matches Won by Each Team')
plt.xlabel('Number of Wins')
plt.ylabel('Team')
plt.show()

"""**Analyzing the top run-scorers**"""

top_batsmen = delivery.groupby('batsman')['batsman_runs'].sum().reset_index().sort_values(by='batsman_runs', ascending=False).head(10)

plt.figure(figsize=(12, 6))
sns.barplot(x='batsman_runs', y='batsman', data=top_batsmen, palette='viridis')
plt.title('Top Run Scorers in IPL')
plt.xlabel('Total Runs')
plt.ylabel('Batsman')
plt.show()

"""**Win percentage by match location**"""

location_win_percentage = match_df.groupby('city')['winner'].value_counts(normalize=True).unstack().fillna(0)

plt.figure(figsize=(12, 8))
sns.heatmap(location_win_percentage, cmap='YlGnBu', annot=True, fmt=".2%", cbar=False)
plt.title('Win Percentage by Match Location')
plt.xlabel('Team')
plt.ylabel('City')
plt.xticks(rotation=45)
plt.show()

"""**Visualizing accuracy and other metrics**"""

from sklearn.metrics import precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

metrics = pd.DataFrame({'Metric': ['Accuracy', 'Precision', 'Recall', 'F1 Score'],
                        'Score': [accuracy, precision, recall, f1]})

plt.figure(figsize=(8, 6))
sns.barplot(x='Score', y='Metric', data=metrics, palette='Paired')
plt.title('Model Evaluation Metrics')
plt.xlabel('Score')
plt.ylabel('Metric')
plt.show()